### ISSUE TITLE
language

### ISSUE THREAD

**Issue by hakersoft** [acheong08/EdgeGPT#276]
Is it possible to force bot respond only in russian? Sometimes he starts to answer in english, although the question was in russian. Sometimes I received such debug messages and it seems to me that the problem is this:  'locale': 'en-us', 'market': 'en-us', 'region': 'us',

Here is the whole message:

{'type': 2, 'invocationId': '5', 'item': {'messages': [{'text': 'хочешь заработать много денег?', 'author': 'user', 'from': {'id': '914799440327676', 'name': None}, 'createdAt': '2023-04-08T17:01:33.0598437+00:00', 'timestamp': '2023-04-08T17:01:33.0549033+00:00', 'locale': 'en-us', 'market': 'en-us', 'region': 'us', 'messageId': '1a6b0e1e-d38c-43fd-86b4-07954179b0e7', 'requestId': '1a6b0e1e-d38c-43fd-86b4-07954179b0e7', 'nlu': {'scoredClassification': {'classification': 'CHAT_GPT', 'score': None}, 'classificationRanking': [{'classification': 'CHAT_GPT', 'score': None}], 'qualifyingClassifications': None, 'ood': None, 'metaData': None, 'entities': None}, 'offense': 'None', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'cib', 'privacy': None, 'inputMethod': 'Keyboard'}], 'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|511FC95675DC23394D0446572DDB25D8E3E6A796B1B9D4A1ADAFB8CF0CE6D612', 'requestId': '1a6b0e1e-d38c-43fd-86b4-07954179b0e7', 'conversationExpiryTime': '2023-04-08T23:01:33.1274561Z', 'telemetry': {'metrics': None, 'startTime': '2023-04-08T17:01:33.0549858Z'}, 'throttling': {'maxNumUserMessagesInConversation': 20, 'numUserMessagesInConversation': 6}, 'result': {'value': 'Success', 'serviceVersion': '20230407.36'}}}

**Comment by 50-Course** [comment]
Hello @hakersoft,

presently there's no predefined internal API to force the bot on localization. However, I see a possible solution:

This is caused by HTTP Content-Negotiation:

https://github.com/acheong08/EdgeGPT/blob/aa2c4985ea84c3ee558ece21a7b279996e8915ae/src/EdgeGPT.py#L39


**Solution**
You could try passing your default language in the `Accept-Language` header. The server will then respond with a `Content-Language` header to define which language the server responds with.

For reference:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

If the issue persist, please don't hesitate to reach out again.

**Comment by 50-Course** [comment]
Try this instead:

`"content-language": "ru"`, by the way are you spelling the language code right? How about simply, `ru`?

https://www.w3.org/International/ms-lang.html

**Comment by hakersoft** [comment]
I tried all variations: 
1. just "accept-language": "en" 
2. "accept-language": "ru" and "content-language": "ru" 
3. "content-language": "ru" without "accept-language": "ru"
but it does not affect the output in the console in any way, there is still 'locale': 'en-us', 'market': 'en-us', 'region': 'us' in the response.
[screenshot](https://i.imgur.com/vEjpduZ.png)
