### ISSUE TITLE
[Feature Request]: Cookies类的dirpath = Path("./").resolve()，建议文件夹路径改为传参

### ISSUE THREAD

**Issue by JimouChen** [acheong08/EdgeGPT#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

- 把`dirpath`里面的路径改为传参，这样`bing_cookies_*json`在很多个的情况下就不会都堆积在根目录，例如放到一个指定的目录下：
```dirpath = Path("./conf/").resolve()```

### Proposed workflow

- 例如可以在`Query`类多加个参数，或者对路径多做一步解析.....

**Comment by PFython** [comment]
@acheong08 - This relates to Query so I'm happy if you want to assign the Issue to me.  I don't understand the Chinese (?) characters I'm afraid, so will need help understanding this.  Google translation helps, but not totally! :)

**Comment by acheong08** [comment]
My Chinese abilities are also limited especially since I just moved out of China (deleted the language from my brain). 

My understanding is:
[Feature request]: Pass directory of cookies to Query class
Reasoning: When a developer has many projects, they do not want duplicate cookie files. Passing a `dirpath` allows them to put the cookie files all in one place like `~/.cookies/bing_cookies_*json`

`dirpath` should be `cookie_filepath` imo to make it more intuitive.

**Comment by JimouChen** [comment]
> My Chinese abilities are also limited especially since I just moved out of China (deleted the language from my brain).
> 
> My understanding is: [Feature request]: Pass directory of cookies to Query class Reasoning: When a developer has many projects, they do not want duplicate cookie files. Passing a `dirpath` allows them to put the cookie files all in one place like `~/.cookies/bing_cookies_*json`
> 
> `dirpath` should be `cookie_filepath` imo to make it more intuitive.

Yes, your understanding is correct

**Comment by PFython** [comment]
Many thanks!  I'm reworking this currently and hope to submit a new Pull Request in a day or two, but in the meantime the solution is simpler than you might have realised...

`dirpath` is a a class attribute already, so you can simply set it with `Cookie.dirpath = Path("~/.cookies/bing")` before creating a query.  No need to program extra logic for the function to take dirpath - Python already does this with normal "." notation :)

Similarly if you want to change the filename pattern from what I've suggested: `Cookie.search_pattern = "edge-cookies-*.json"`

As for naming, again because `dirpath` and `search_pattern` are attributes of the `Cookie` class, their name is clear because of the namespace and `Cookie.cookie_filepath` and `Cookie.cookie_search_pattern` would be redundant I suggest.

**Comment by MonsterDruide1** [comment]
Duplicate/same as #462

**Comment by PFython** [comment]
See https://github.com/acheong08/EdgeGPT/pull/507

**Comment by JimouChen** [comment]
ok, I have modified this question privately according to my own needs, and I can close the issue
