### ISSUE TITLE
[Bug]: can not run

### ISSUE THREAD

**Issue by leyandh** [acheong08/EdgeGPT#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

ImportError: attempted relative import with no known parent package

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

run

### Version where the problem happens

Latest version

### What Python version are you running this with?

3.9

### Command Line Arguments

```Shell
python EdgeGPT.py
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\26306\Desktop\EdgeGPT\src\EdgeGPT\EdgeGPT.py", line 10, in <module>
    from .chathub import *
ImportError: attempted relative import with no known parent package
```

**Comment by Meshwa428** [comment]
Why do you want to run it directly, you should use the module in your .py file, and also use the asyncio, or if you don't want to write the whole code, then its also provided in the readme file, you can just copy and paste it and do your modifications as you need

**Comment by PaTTeeL** [comment]
> Why do you want to run it directly, you should use the module in your .py file, and also use the asyncio, or if you don't want to write the whole code, then its also provided in the readme file, you can just copy and paste it and do your modifications as you need


I'm also confused by how can I test the latest modifications or new features without running code directly?

I used to run EdgeGPT by using `git -C ~/BingGPT-Python pull --no-edit --rebase --strategy-option=ours origin; python3 ~/BingGPT-Python/src/EdgeGPT.py` 4 weeks ago in the command line, and now it does not work any more since the src/EdgeGPT.py moved to src/EdgeGPT/EdgeGPT.py.
