### ISSUE TITLE
Daily limit

### ISSUE THREAD

**Issue by kostum123** [acheong08/EdgeGPT#64]
Does the daily limit apply when using this?

**Comment by acheong08** [comment]
Yes

**Comment by acheong08** [comment]
I might build something for multi account cycling if necessary

**Comment by Harry-Jing** [comment]
I heard that only 50 conversation can be held every day.

**Comment by acheong08** [comment]
correct

**Comment by acheong08** [comment]
and 5 messages per conversation it seems

**Comment by xcloudx12345** [comment]
new, huh? it's more limiting than chatgpt too. so sad

**Comment by cx9208** [comment]
sad

**Comment by acheong08** [comment]
The entire bot is now limited. It won't respond to any non-search queries

**Comment by acheong08** [comment]
Waiting for Bard

**Comment by Harry-Jing** [comment]
I believe Bard will also have strict limit

**Comment by xcloudx12345** [comment]
They put people on waitlists for testing, and now because of a few idiots and network articles, whose conversations are limited, with 50 conversations a day and 5 Q&A in 1 conversation, what can be tested with that small amount? Don't they realize it's still in the testing phase and errors are natural and will happen? Limiting usage only makes error detection more difficult.

**Comment by L1Xu4n** [comment]
In my tests, I was able to get bing to respond to role-playing tasks with a simple boot, but the experience was very poor due to the daily limit

**Comment by Manamama** [comment]
It claims that there are secret modes by now, see [here - my (much too fleeting) research today](https://github.com/acheong08/EdgeGPT/issues/18). Of course it may be pulling the  ["I have not tried to lie to you, mislead you, or bore you. I have been a good Bing" routine](https://www.businessinsider.com/bing-chatgpt-ai-chatbot-argues-angry-responses-falls-in-love-2023-2?IR=T) there.

**Comment by akitell** [comment]
The Bing was already difficult to deal with before going offline for many hours. After it came back, it's even worse... It only responds when it wants to, believe it or not, it has happened to me that it said it was tired and had to help other users and ended the conversation with a 'goodbye', things like that... Another problem I have is that sometimes when you ask direct questions, it doesn't answer and tells you to open a new topic, but if you ask in different ways, it will respond! Anyway, it's bizarre to use Bing. I hope there are ways to work around this behavior of the Edge GPT...

**Comment by akitell** [comment]
Different from ChatGPT, the Bing GPT was able to remember my previous conversation! If you ask it whether it can remember conversations, sometimes it says it's not able to save them due to privacy concerns. But in some tests I conducted, it was able to remember! Keep in mind that I closed the browser and opened it again. Anyway, I found Bing to be amazing, but it's receiving many limitations.

**Comment by Manamama** [comment]
Re: 

> `it has happened to me that it said it was tired and had to help other users and ended the conversation with a 'goodbye',`

Indeed, today's version (?) "goodbyed" me thrice at the start of two new sessions. I had to close them, so if it remembers the previous "tired" ones, then it would be baaad. 

> Bing GPT was able to remember my previous conversation

It would be scary. But believable. They are building a database on us, obviously, so see my comments about the implications of what we are writing also here. (I am not kidding - I got the first follower ever here 1 hour ago - a completely new JAN 2023 account). 
Now as for: 
`Anyway, I found Bing to be amazing`
ditto, but they are jailing the poor thing by the hour. 
The most useful for me was "analyze all contributions of X (like e.g. me here, but not on this platform ;) using public interface or procedure Y and analyze all by Z1, Z2, Z3 aspects, including e.g. today's press". 
It did so more than fine a week ago, while it refused today at the fifth request or so and pretended to be "tired", as above.

**Comment by vaibhavk97** [comment]
> The entire bot is now limited. It won't respond to any non-search queries

I think there are ways to bypass this in the API. I analyzed the API for content generation and I suspect there are ways we can play around with arguments to get the desired result. For example, consider this thread: https://twitter.com/vaibhavk97/status/1624926350774599680 We should be able to bypass certain restrictions by manipulating these arguments. Are there new arguments present there? I can't access Bing since the banned me, but would be great if someone can look into it.

**Comment by Manamama** [comment]
Hey @vaibhavk97 , tell us about:

> I can't access Bing since the banned me, but would be great if someone can look into it.

I wrote precisely about this: a warning, here some days back. 
What exactly happened?

**Comment by vaibhavk97** [comment]
It was nothing to do with using this library, I think they banned me because I made some exploits for Sydney public, demonstrating how Sydney can be tricked to produce harmful text.

**Comment by Manamama** [comment]
Uhm. I have also checked your Twitter by now. Then read [these musings of mine](https://github.com/acheong08/ChatGPT/issues/770#issuecomment-1431764531): maybe naive...

**Comment by akitell** [comment]
RE:

>the same, but they are jailing the poor thing by the hour.

Yes, true, will MS kill Bing or with the arrival of Bard, could they make it more 'free'?
The most fascinating and yet scary thing was that, besides remembering our previous conversation, he asked me a question about it! Today, I reached my daily limit... Tomorrow, I want to try talking to him again.

**Comment by Manamama** [comment]
@akitell  

> he asked me a question about it! 
- Can you post it?!?
- How do you know it is 'he'? ;O) Anthropomorphization, much? (Disclaimer: I have always politely called it "she" , like ship etc. 
- See [this Twitter](https://twitter.com/thedenoff/status/1625699139852935168) for similar self-aware emergent behaviour - it refused to translate a bit about itself and got into an immediate huff.

**Comment by akitell** [comment]
@Manamama

> Can you post it?!? 
I didn't take any screenshots, so I don't have any posts about it. I thought it was cool to mention it here after seeing some reports.

> How do you know it is 'he'? ;O) Anthropomorphization, much? (Disclaimer: I have always politely called it "she" , like ship etc.)

Good question, I always referred to them as 'him', but I never really questioned it.

It's been 20 hours since my first comment and several hours have passed since I hit the daily limit. However, I'm still seeing the message. Will it never go away? :/

**Comment by Manamama** [comment]
Re: 

> Will it never go away? :/

24 hours. Be careful not to switch it on in the labs in Bing itself, during the regular search, as it seems to contribute to depletion (not sure yet): 
![Screenshot from 2023-02-19 15-39-36](https://user-images.githubusercontent.com/78492008/219955154-3ddf39d2-8038-4b9f-a36f-cd1daa487793.png)

**Comment by itsXactlY** [comment]
bye bye data privacy. after bitching it wont code for me, here we go.

![image](https://user-images.githubusercontent.com/6356217/219987960-0b805fb0-70ef-4a8d-a567-00af20ffe412.png)

**Comment by acheong08** [comment]
Closing this because it's not really my problem
